language: node_js
node_js:
  - "lts/*"
script: KARMA_OPTS="--browsers Firefox" make -e test
before_script:
  - export DISPLAY=:99.0
services:
  - xvfb
addons:
  firefox: latest
arch:
  - amd64
  - ppc64le
